/* Backup Full*/
BACKUP DATABASE [WWI] TO  DISK = N'D:\Work\MSSQL15.MSSQLSERVER\MSSQL\Backup\WWI.bak'
WITH NOFORMAT,
NOINIT,
NAME = N'WWI-Full Database Backup',
SKIP,
NOREWIND,
NOUNLOAD,
STATS = 10
GO

/*Backup Differential*/
BACKUP DATABASE [WWI] TO  DISK = N'D:\Work\MSSQL15.MSSQLSERVER\MSSQL\Backup\WWI.bak'
WITH  DIFFERENTIAL,
NOFORMAT,
NOINIT,
NAME = N'WWI-Full Database Backup',
SKIP,
NOREWIND,
NOUNLOAD,
STATS = 10
GO

/*Backup Transactions*/
BACKUP LOG [WWI] TO  DISK = N'D:\Work\MSSQL15.MSSQLSERVER\MSSQL\Backup\WWI.bak'
WITH NOFORMAT,
NOINIT,
NAME = N'WWI-Full Database Backup',
SKIP,
NOREWIND,
NOUNLOAD,
STATS = 10
GO